services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "birdseye", "-U", "birdseye"]
      interval: 1s
    environment:
      - POSTGRES_USER=birdseye
      - POSTGRES_PASSWORD=birdseye
      - POSTGRES_DB=birdseye

  api:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - DATABASE_URL=postgresql+psycopg_async://birdseye:birdseye@db/birdseye
    command: sh startlocal.sh
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock

volumes:
  pgdata:
