name: Lint, Typecheck, Test

on: [push]

env:
  DATABASE_URL: "sqlite+aiosqlite://"

jobs:
  test:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: "0.7.20"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run linter
        run: uv run ruff check --output-format=github

      - name: Run formatter
        run: uv run ruff format --diff

      - name: Run typechecker
        run: uv run pyright

      - name: Run tests
        run: uv run pytest
